Img update, settings info added
GispoCoding/GP004_Johdanto_GeoServerin_kayttoon pull request #23
Opened 2024-09-24 12:07 UTC by jeeemil

- Deleted a hint-box, where there's text that doesn't apply to the training environment GeoServer anymore
- Split up a table to corresponding menus in GeoServer
- Updated a picture with the current data_directory path

2024-09-25 15:43 UTC, ismogis requested changes

2024-09-25 15:43 UTC, ismogis commented on src/02_harjoitus_2.Rmd
> +| **Raster Access**                    | WCS-palvelun muistinhallintaan ja palvelun optimointiin liittyviä asetuksia |
@jeeemil Nämä vaikuttavat käsittääkseni myös muuhun rasterinkäsittelyyn (esim. WMS). Olisiko parempi "Rasteriaineiston käsittelyyn liittyviä muisti- ja CPU-asetuksia"?

2024-09-26 05:25 UTC, jeeemil commented on src/02_harjoitus_2.Rmd
> +| **Raster Access**                    | WCS-palvelun muistinhallintaan ja palvelun optimointiin liittyviä asetuksia |
@ismogis Totta! Joo toi on paljon parempi. Mä teen uuden committin.

2024-09-26 06:06 UTC, ismogis approved these changes

2024-09-26 11:50 UTC, merged